import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, cp, readFile, writeFile, rm, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { csv, loadDataset, acquire } from '../src/data.js';
import { partition, serializePredictions, type RoutingEvidence } from '../src/split.js';
import { routers } from '../src/routers.js';
import { Tfidf, similarity } from '../src/features.js';
import { evaluate } from '../src/evaluate.js';
import { experiment, main } from '../src/cli.js';
import { preexecution, type Options, type Dataset, type Prediction } from '../src/types.js';
const fixture=resolve('research/cold-start/fixtures');
const options:Options={mode:'task-holdout',seed:42,k:3,minimumNeighbors:3,metric:'cosine',features:'text-dimension'};
const predict=(data:Dataset,o=options)=>{const s=partition(data,o);return {s,p:routers(s.evidence,o).flatMap(r=>s.tasks.map(t=>({router:r.name,taskId:t.taskId,...r.predict(preexecution(t))}))) };};
async function temporary(fn:(dir:string)=>Promise<void>){const dir=await mkdtemp(join(tmpdir(),'koda-cold-research-'));try{await fn(dir);}finally{await rm(dir,{recursive:true,force:true});}}
async function score(data:Dataset,o=options) {const {s,p}=predict(data,o);let result!:ReturnType<typeof evaluate>;await temporary(async d=>{const path=join(d,'predictions.jsonl');await writeFile(path,serializePredictions(p));result=evaluate(p,await s.releaseGroundTruth(path,p));});return result;}

test('RFC4180 CSV quotes, newlines, empty fields and errors',()=>{assert.deepEqual(csv('a,b\r\n"x,y","a""b"\r\n"two\nlines",\r\n'),[{a:'x,y',b:'a"b'},{a:'two\nlines',b:''}]);assert.throws(()=>csv('a,b\n1\n'),/column/);assert.throws(()=>csv('a,b\n"unfinished'),/Unterminated/);assert.throws(()=>csv('a,a\n1,2'),/header/);});
test('normalization preserves real fields, unknown revisions, raw provenance and counts',async()=>{const data=await loadDataset(fixture);assert.equal(data.tasks.length,12);assert.equal(data.outcomes.length,36);assert.equal(data.summary.completeMatrices,12);assert.equal(data.models.length,3);assert.equal(data.outcomes[0]!.modelRevision,null);assert.match(data.outcomes[0]!.rawRecordReference,/csv:row:/);assert.equal(data.outcomes[0]!.sourceRevisionOrFingerprint.length,64);assert.equal(data.summary.costCoverage,1);});
test('missing costs/tokens/latency stay null without extrapolation',async()=>{await temporary(async d=>{await cp(fixture,d,{recursive:true});for(const f of ['id_results_long.csv','id_probing_results_long.csv']) {let s=await readFile(join(d,f),'utf8');s=s.replace('0.01,10,5,15,100,',',,,,,');await writeFile(join(d,f),s);}const data=await loadDataset(d);const row=data.outcomes.find(o=>o.taskId==='probing-0' && o.modelId==='model-a')!;assert.equal(row.costUsd,null);assert.equal(row.latencyMs,null);assert.equal(row.inputTokens,null);});});
test('raw files stay unchanged across normalization',async()=>{const before=await readFile(join(fixture,'id_results_long.csv'),'utf8');await loadDataset(fixture);assert.equal(await readFile(join(fixture,'id_results_long.csv'),'utf8'),before);});
test('duplicate task/model observations fail loudly',async()=>{await temporary(async d=>{await cp(fixture,d,{recursive:true});const f=join(d,'id_probing_results_long.csv'),s=await readFile(f,'utf8');await writeFile(f,s+s.split('\n')[1]+'\n');await assert.rejects(loadDataset(d),/Duplicate task\/model/);});});
test('conflicting combined outcomes fail instead of choosing one',async()=>{await temporary(async d=>{await cp(fixture,d,{recursive:true});const f=join(d,'id_results_long.csv'),s=await readFile(f,'utf8');await writeFile(f,s.replace('model-a,1,','model-a,0,'));await assert.rejects(loadDataset(d),/mismatch/);});});
test('missing joins, unknown models, invalid scores and split conflicts fail',async()=>{for(const [from,to,pattern] of [['probing-0','unknown-task',/join/],['model-a','unknown-model',/Unknown model/],['model-a,1,','model-a,NaN,',/Invalid outcome/],['probing,train','id_test,train',/split/]] as const) await temporary(async d=>{await cp(fixture,d,{recursive:true});const f=join(d,'id_probing_results_long.csv');await writeFile(f,(await readFile(f,'utf8')).replace(from,to));await assert.rejects(loadDataset(d),pattern);});});
test('missing task text is null and prominently audited, never derived from ID',async()=>{await temporary(async d=>{await cp(fixture,d,{recursive:true});for(const f of ['id_tasks.jsonl','id_probing_tasks.jsonl','id_test_tasks.jsonl']) {const rows=(await readFile(join(d,f),'utf8')).trim().split('\n').map(l=>{const r=JSON.parse(l);delete r.prompt;return JSON.stringify(r);});await writeFile(join(d,f),rows.join('\n')+'\n');}const data=await loadDataset(d);assert.equal(data.summary.missingTaskText,10);assert.equal(data.tasks.find(t=>t.taskSplit==='probing')!.taskText,null);assert.match(JSON.stringify(data.summary.warnings),/ID_TASK_TEXT_UNAVAILABLE/);});});
test('source splits give probing-only evidence and disjoint test tasks',async()=>{const data=await loadDataset(fixture),s=partition(data,options);assert.equal(s.evidence.tasks.length,6);assert.equal(s.tasks.length,4);assert.ok(s.evidence.tasks.every(t=>t.task.taskSplit==='probing'));assert.ok(s.tasks.every(t=>t.taskSplit==='id_test'));assert.ok(!s.evidence.tasks.some(t=>s.tasks.some(e=>t.task.taskId===e.taskId)));assert.equal(Object.isFrozen(s.evidence),true);});
test('seeded task holdout and limit are deterministic and outcome-blind',async()=>{const d=await loadDataset(fixture),o={...options,taskHoldout:.5,limit:2};const a=partition(d,o);const altered=structuredClone(d);altered.outcomes.forEach(x=>x.outcome=1-x.outcome);const b=partition(altered,o);assert.deepEqual(a.split.evaluationTaskIds,b.split.evaluationTaskIds);assert.equal(a.tasks.length,2);assert.ok(a.tasks.every(t=>t.taskSplit==='probing'));assert.ok(!a.evidence.tasks.some(t=>a.tasks.some(e=>t.task.taskId===e.taskId)));});
test('OOD never enters ID training evidence',async()=>{const d=await loadDataset(fixture),s=partition(d,{...options,mode:'ood'});assert.equal(s.tasks.length,2);assert.ok(s.tasks.every(t=>t.taskSplit==='ood'));assert.ok(s.evidence.tasks.every(t=>t.task.taskSplit==='probing'));assert.throws(()=>partition(d,{...options,mode:'ood',taskHoldout:.2}),/not applicable/);});
test('held-out model labels are inaccessible, unavailable estimate remains unavailable',async()=>{const d=await loadDataset(fixture),o={...options,mode:'model-holdout' as const,holdoutModel:'model-a'};const {s,p}=predict(d,o);assert.ok(s.evidence.tasks.every(t=>t.observations.every(x=>x.modelId!=='model-a')));assert.equal(s.split.status,'UNSEEN_MODEL_SELECTION_NOT_SUPPORTED_IN_PHASE_1');assert.ok(p.filter(p=>p.router==='kNN').every(p=>p.estimates['model-a']===null && p.model!=='model-a'));});
test('hidden test labels change neither predictions nor neighbors nor train fingerprint',async()=>{const d=await loadDataset(fixture),a=predict(d);const hidden=structuredClone(d);hidden.outcomes.filter(o=>o.taskSplit!=='probing').forEach(o=>{o.outcome=1-o.outcome;o.costUsd=999;});const b=predict(hidden);assert.deepEqual(a.p,b.p);assert.equal(a.s.split.trainFingerprint,b.s.split.trainFingerprint);assert.deepEqual(a.s.split.evaluationTaskIds,b.s.split.evaluationTaskIds);});
test('held-out model labels cannot influence predictions',async()=>{const d=await loadDataset(fixture),o={...options,mode:'model-holdout' as const,holdoutModel:'model-a'};const a=predict(d,o).p;const altered=structuredClone(d);altered.outcomes.filter(o=>o.modelId==='model-a').forEach(o=>o.outcome=1-o.outcome);assert.deepEqual(a,predict(altered,o).p);});
test('oracle/full matrix cannot enter normal router interface',async()=>{assert.throws(()=>routers({kind:'evaluation-ground-truth',outcomes:[]} as unknown as RoutingEvidence,options),/RoutingEvidence/);assert.throws(()=>routers({kind:'routing-evidence',tasks:[],models:[]} as RoutingEvidence,options),/RoutingEvidence/);const d=await loadDataset(fixture);assert.ok(!routers(partition(d,options).evidence,options).some(r=>r.name.toLowerCase().includes('oracle')));await assert.rejects(main(['eval','--router','oracle']),/Unknown/);});
test('ground truth releases only after complete byte-identical predictions are on disk',async()=>{const {s,p}=predict(await loadDataset(fixture));await temporary(async d=>{const f=join(d,'predictions.jsonl');await assert.rejects(s.releaseGroundTruth(f,p));await writeFile(f,'[]');await assert.rejects(s.releaseGroundTruth(f,p),/finalized/);const partial=p.slice(1);await writeFile(f,serializePredictions(partial));await assert.rejects(s.releaseGroundTruth(f,partial),/Incomplete/);await writeFile(f,serializePredictions(p));assert.equal((await s.releaseGroundTruth(f,p)).kind,'evaluation-ground-truth');});});
test('Global best uses training quality, not evaluation outcome',async()=>{const d=await loadDataset(fixture),a=predict(d);assert.ok(a.p.filter(p=>p.router==='Global best').every(p=>p.model==='model-c'));const r=await score(d);assert.equal(r.metrics['Global best']!.resolvedRate,.5);assert.equal(r.metrics.kNN!.resolvedRate,1);});
test('Global cheapest refuses partial costs; cost aggregate N/A for a missing selected cost',async()=>{const d=await loadDataset(fixture);d.outcomes.find(o=>o.taskId==='probing-0' && o.modelId==='model-a')!.costUsd=null;assert.ok(predict(d).p.filter(p=>p.router==='Global cheapest').every(p=>p.model===null));d.outcomes.find(o=>o.taskId==='id_test-0' && o.modelId==='model-a')!.costUsd=null;const r=await score(d);assert.equal(r.metrics['Always(model-a)']!.costPerTask,null);assert.equal(r.metrics['Always(model-a)']!.costCoverage,.75);});
test('feature representation ignores task ID and outcome; TF-IDF vocabulary train-only',()=>{const extractor=new Tfidf([{text:'sum math',dimension:'arithmetic'}],'text');assert.deepEqual([...extractor.transform({text:'sum unseen',dimension:null}).keys()],['sum']);const distance=similarity('cosine');assert.equal(distance.compare(extractor.transform({text:'sum',dimension:null}),extractor.transform({text:'sum',dimension:null})),1);assert.equal(similarity('jaccard').compare(new Map([['a',1]]),new Map([['a',3],['b',1]])),.5);});
test('feature ties include boundary peers; renaming IDs cannot change estimates or selection',async()=>{const d=await loadDataset(fixture),o={...options,k:1,minimumNeighbors:1,features:'dimension' as const};const a=predict(d,o).p.filter(p=>p.router==='kNN');const changed=structuredClone(d);const names=new Map(changed.tasks.map((t,i)=>[t.taskId,`renamed-${100-i}`]));changed.tasks.forEach(t=>t.taskId=names.get(t.taskId)!);changed.outcomes.forEach(t=>t.taskId=names.get(t.taskId)!);const b=predict(changed,o).p.filter(p=>p.router==='kNN');const compact=(p:Prediction[])=>p.map(x=>JSON.stringify([x.model,x.estimates])).sort();assert.deepEqual(compact(a),compact(b));assert.ok(a.every(p=>p.neighbors.length===3));});
test('insufficient neighbors cause abstention, never hidden/global score fallback',async()=>{const d=await loadDataset(fixture),s=partition(d,options),r=routers(s.evidence,options).find(r=>r.name==='kNN')!;const p=r.predict({text:'unknown unique vocabulary',dimension:null});assert.equal(p.model,null);assert.ok(Object.values(p.estimates).every(x=>x===null));});
test('exact metrics: solve, regret, catastrophe, cost, latency and posthoc best static',async()=>{const r=await score(await loadDataset(fixture));const a=r.metrics['Always(model-a)']!;assert.equal(a.resolvedRate,.5);assert.equal(a.meanRegret,.5);assert.equal(a.p95Regret,1);assert.equal(a.catastrophicMissRate,.5);assert.equal(a.costPerResolved,.02);assert.equal(a.latencyPerTaskMs,100);assert.equal(r.metrics.kNN!.costPerResolved,.015);assert.equal(r.metrics.kNN!.meanRegret,0);assert.equal(r.metrics['Oracle (posthoc)']!.resolvedRate,1);assert.equal(r.comparisons.knnSolveDeltaVsBestStatic,.5);});
test('continuous regret uses actual score, complete solve remains exactly one',async()=>{const d=await loadDataset(fixture);d.outcomes.find(o=>o.taskId==='id_test-0' && o.modelId==='model-a')!.outcome=.5;const r=await score(d);assert.equal(r.metrics['Always(model-a)']!.resolvedRate,.25);assert.equal(r.metrics['Always(model-a)']!.meanRegret,.625);});
test('incomplete paired task matrices excluded and reported, not imputed',async()=>{const d=await loadDataset(fixture);d.outcomes=d.outcomes.filter(o=>!(o.taskId==='id_test-0' && o.modelId==='model-a'));const s=partition(d,options);assert.equal(s.tasks.length,3);assert.equal(s.split.excluded.length,1);assert.equal(s.split.excluded[0]!.reason,'incomplete candidate outcome matrix');});
test('artifacts are separate, reproducible, and never silently overwritten',async()=>{await temporary(async d=>{const a=join(d,'nested','a'),b=join(d,'nested','b');await experiment(fixture,a,options);await experiment(fixture,b,options);for(const f of ['predictions.jsonl','metrics.json','split.json','ground-truth.jsonl','dataset-fingerprint.json']) assert.equal(await readFile(join(a,f),'utf8'),await readFile(join(b,f),'utf8'));assert.ok((await readdir(a)).includes('config.json'));await assert.rejects(experiment(fixture,a,options),/EEXIST/);});});
test('snapshot tampering fails validation',async()=>{await temporary(async d=>{await cp(fixture,d,{recursive:true});await writeFile(join(d,'snapshot.json'),JSON.stringify({revision:'fake',files:{}}));await assert.rejects(loadDataset(d),/fingerprint mismatch/);});});
test('CLI rejects unsupported models/modes/metrics and invalid neighbor configuration',async()=>{const d=await loadDataset(fixture);assert.throws(()=>partition(d,{...options,models:['unknown']}),/Unknown/);assert.throws(()=>partition(d,{...options,mode:'invalid' as Options['mode']}),/mode/);assert.throws(()=>routers(partition(d,options).evidence,{...options,k:0}),/neighbor/);assert.throws(()=>similarity('unknown' as 'cosine'),/metric/);});

test('acquisition pins immutable revision and hashes unchanged downloads, with no provider calls',async()=>{await temporary(async d=>{const requests:string[]=[];const original=globalThis.fetch;const sha='a'.repeat(40);const files=await readdir(fixture);globalThis.fetch=(async (url:unknown)=>{const u=String(url);requests.push(u);if(u.includes('/api/datasets/')) return new Response(JSON.stringify({sha,siblings:files.map(rfilename=>({rfilename}))}));assert.ok(u.startsWith(`https://huggingface.co/datasets/Lance1573/CodeRouterBench/resolve/${sha}/`));return new Response(await readFile(join(fixture,u.split('/').at(-1)!),'utf8'));}) as typeof fetch;try {const target=join(d,'nested','cache');await acquire(target);const loaded=await loadDataset(target);assert.equal(loaded.fingerprint.revision,sha);assert.equal(requests.length,11);await assert.rejects(acquire(target),/already exists/);assert.equal((await loadDataset(target)).fingerprint.revision,sha);}finally{globalThis.fetch=original;}});});
